### ISSUE TITLE
Support for lists of numpy arrays in model parameters

### ISSUE THREAD

**Issue by gegose** [sherpaai/Sherpa.ai-Federated-Learning-Framework#155]

**Comment by xehartnort** [comment]
I've been thinking about this issue and the solution I've come up with is adding seriliaze/deserialize methods to the models so that the input for the aggregation mechanism is always a serialized list of numpy arrays, that is, a "flattened numpy array". What do you think?

Note that not all models might be serializable, which suggests a SerializeModel abstract class might be useful.
